spring.application.name=userprofile-service

server.port=8083

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka.client.service-url.defaultZone=${EUREKA_SERVER}
eureka.client.register-with-eureka= true
eureka.client.fetch-registry: true

spring.kafka.topic=user-profile
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#spring.jpa.hibernate.ddl-auto=update

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
